{
 "title": "window-multi-rf",
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  {
   "title": "Output Binary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "output_binary over time per ground_truth",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 11, "x": 0, "y": 1 },
     "targets": [
      {
       "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"window-multi-rf\" and (r._field == \"ground_truth\" or r._field == \"output_binary\"))\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group(columns: [\"ground_truth\"])\r\n  |> rename(columns: {\"output_binary\": \"ground_truth -\"})"
      }
     ]
    },
    {
     "title": "Output Binary = 1",
     "type": "table",
     "description": "Each table represents each ground truth in the measurement",
     "gridPos": { "h": 15, "w": 13, "x": 11, "y": 1 },
     "targets": [
      {
       "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"window-multi-rf\" and (r._field == \"ground_truth\" or r._field == \"output_binary\"))\r\n  |> keep(columns: [\"_time\", \"ip_src_addr\", \"ip_dst_addr\", \"_value\", \"_field\", \"ip_src_port\", \"ip_dst_port\"])\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.output_binary == 1)\r\n  |> group(columns: [\"ground_truth\"])"
      }
     ]
    },
    {
     "title": "Total of packets per ground_truth",
     "type": "piechart",
     "gridPos": { "h": 13, "w": 8, "x": 0, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"window-multi-rf\" and (r._field == \"ground_truth\" or r._field == \"output_binary\"))\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group(columns: [\"ground_truth\"])\r\n  |> rename(columns: {\"output_binary\": \"ground_truth -\"})"
      }
     ]
    },
    {
     "title": "Total of packets with output_binary = 1 per ground_truth",
     "type": "piechart",
     "gridPos": { "h": 13, "w": 8, "x": 8, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"window-multi-rf\" and (r._field == \"ground_truth\" or r._field == \"output_binary\"))\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.output_binary == 1)\r\n  |> group(columns: [\"ground_truth\"])\r\n  |> rename(columns: {\"output_binary\": \"ground_truth -\"})"
      }
     ]
    },
    {
     "title": "Total of packets with output_binary = 0 per ground_truth",
     "type": "piechart",
     "gridPos": { "h": 13, "w": 8, "x": 16, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"window-multi-rf\" and (r._field == \"ground_truth\" or r._field == \"output_binary\"))\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.output_binary == 0)\r\n  |> group(columns: [\"ground_truth\"])\r\n  |> rename(columns: {\"output_binary\": \"ground_truth -\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Data size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Histogram IP Data Size && TCP Data Size",
     "type": "histogram",
     "gridPos": { "h": 12, "w": 14, "x": 0, "y": 46 },
     "targets": [
      {
       "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"window-multi-rf\" and (r._field == \"ip_data_size\" or r._field == \"tcp_data_size\"))\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) }))\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> keep(columns: [\"ip_data_size\", \"tcp_data_size\"])"
      }
     ]
    },
    {
     "title": "IP Data Size - max",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 14, "y": 46 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"window-multi-rf\")\r\n  |> filter(fn: (r) => r._field == \"ip_data_size\")\r\n  |> keep(columns: [\"_value\"])\r\n  |> max()"
      }
     ]
    },
    {
     "title": "TCP Data Size - max",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 46 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"window-multi-rf\")\r\n  |> filter(fn: (r) => r._field == \"tcp_data_size\")\r\n  |> keep(columns: [\"_value\"])\r\n  |> max()"
      }
     ]
    },
    {
     "title": "IP Data Size - min",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 14, "y": 50 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"window-multi-rf\")\r\n  |> filter(fn: (r) => r._field == \"ip_data_size\")\r\n  |> keep(columns: [\"_value\"])\r\n  |> min()"
      }
     ]
    },
    {
     "title": "TCP Data Size - mean",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 50 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"window-multi-rf\")\r\n  |> filter(fn: (r) => r._field == \"tcp_data_size\")\r\n  |> keep(columns: [\"_value\"])\r\n  |> mean()"
      }
     ]
    },
    {
     "title": "IP Data Size - mean",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 14, "y": 54 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"window-multi-rf\")\r\n  |> filter(fn: (r) => r._field == \"ip_data_size\")\r\n  |> keep(columns: [\"_value\"])\r\n  |> mean()"
      }
     ]
    },
    {
     "title": "TCP Data Size - min",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 54 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"window-multi-rf\")\r\n  |> filter(fn: (r) => r._field == \"tcp_data_size\")\r\n  |> keep(columns: [\"_value\"])\r\n  |> min()"
      }
     ]
    },
    {
     "title": "IP - IP pair (src -> dst)",
     "type": "barchart",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"window-multi-rf\" and r._field == \"ip_data_size\")\r\n  |> group(columns: [\"ip_src_addr\", \"ip_dst_addr\"])\r\n  |> mean()\r\n  |> map(fn: (r) => ({ ip_data_size: r._value, _field: r.ip_src_addr + \" -> \" +  r.ip_dst_addr}))\r\n"
      }
     ]
    },
    {
     "title": "TCP - IP pair (src -> dst)",
     "type": "barchart",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"window-multi-rf\" and r._field == \"tcp_data_size\")\r\n  |> group(columns: [\"ip_src_addr\", \"ip_dst_addr\"])\r\n  |> mean()\r\n  |> map(fn: (r) => ({ tcp_data_size: r._value, _field: r.ip_src_addr + \" -> \" +  r.ip_dst_addr}))\r\n"
      }
     ]
    },
    {
     "title": "More info: IP + IP pair + Port pair + Ground truth",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 72 },
     "targets": [
      {
       "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"window-multi-rf\" and (r._field == \"ip_data_size\" or r._field == \"ground_truth\"))\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group(columns: [\"ip_src_port\", \"ip_dst_port\", \"ip_src_addr\", \"ip_dst_addr\", \"ground_truth\"])\r\n  |> mean(column: \"ip_data_size\")\r\n  |> map(fn: (r) => ({ ip_data_size: r.ip_data_size, ip_port: r.ip_src_port + \" -> \" +  r.ip_dst_port, ip_pair: r.ip_src_addr + \" -> \" +  r.ip_dst_addr, ground__truth: r.ground_truth}))\r\n"
      }
     ]
    },
    {
     "title": "More info: TCP + IP pair + Port pair + Ground truth",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 72 },
     "targets": [
      {
       "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"window-multi-rf\" and (r._field == \"tcp_data_size\" or r._field == \"ground_truth\"))\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group(columns: [\"ip_src_port\", \"ip_dst_port\", \"ip_src_addr\", \"ip_dst_addr\", \"ground_truth\"])\r\n  |> mean(column: \"tcp_data_size\")\r\n  |> map(fn: (r) => ({ tcp_data_size: r.tcp_data_size, ip_port: r.ip_src_port + \" -> \" +  r.ip_dst_port, ip_pair: r.ip_src_addr + \" -> \" +  r.ip_dst_addr, ground__truth: r.ground_truth}))\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Header size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "IP Header Size - max",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"window-multi-rf\")\r\n  |> filter(fn: (r) => r._field == \"ip_header_size\")\r\n  |> keep(columns: [\"_value\"])\r\n  |> max()"
      }
     ]
    },
    {
     "title": "IP header size - mean",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"window-multi-rf\")\r\n  |> filter(fn: (r) => r._field == \"ip_header_size\")\r\n  |> keep(columns: [\"_value\"])\r\n  |> mean()"
      }
     ]
    },
    {
     "title": "IP header size - min",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"window-multi-rf\")\r\n  |> filter(fn: (r) => r._field == \"ip_header_size\")\r\n  |> keep(columns: [\"_value\"])\r\n  |> min()"
      }
     ]
    },
    {
     "title": "TCP header size - mean",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"window-multi-rf\")\r\n  |> filter(fn: (r) => r._field == \"tcp_header_size\")\r\n  |> keep(columns: [\"_value\"])\r\n  |> mean()"
      }
     ]
    },
    {
     "title": "TCP header size - max",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"window-multi-rf\")\r\n  |> filter(fn: (r) => r._field == \"tcp_header_size\")\r\n  |> keep(columns: [\"_value\"])\r\n  |> max()"
      }
     ]
    },
    {
     "title": "TCP header size - min",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"window-multi-rf\")\r\n  |> filter(fn: (r) => r._field == \"tcp_header_size\")\r\n  |> keep(columns: [\"_value\"])\r\n  |> min()"
      }
     ]
    },
    {
     "title": "IP - IP pair (src -> dst)",
     "type": "barchart",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"window-multi-rf\" and r._field == \"ip_header_size\")\r\n  |> group(columns: [\"ip_src_addr\", \"ip_dst_addr\"])\r\n  |> mean()\r\n  |> map(fn: (r) => ({ ip_header_size: r._value, _field: r.ip_src_addr + \" -> \" +  r.ip_dst_addr}))\r\n"
      }
     ]
    },
    {
     "title": "TCP - IP pair (src -> dst)",
     "type": "barchart",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"window-multi-rf\" and r._field == \"tcp_header_size\")\r\n  |> group(columns: [\"ip_src_addr\", \"ip_dst_addr\"])\r\n  |> mean()\r\n  |> map(fn: (r) => ({ tcp_header_size: r._value, _field: r.ip_src_addr + \" -> \" +  r.ip_dst_addr}))\r\n"
      }
     ]
    },
    {
     "title": "More info: IP + IP pair + Port pair + Ground truth",
     "type": "table",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"window-multi-rf\" and (r._field == \"ip_header_size\" or r._field == \"ground_truth\"))\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group(columns: [\"ip_src_port\", \"ip_dst_port\", \"ip_src_addr\", \"ip_dst_addr\", \"ground_truth\"])\r\n  |> mean(column: \"ip_header_size\")\r\n  |> map(fn: (r) => ({ ip_header_size: r.ip_header_size, ip_port: r.ip_src_port + \" -> \" +  r.ip_dst_port, ip_pair: r.ip_src_addr + \" -> \" +  r.ip_dst_addr, ground__truth: r.ground_truth}))\r\n"
      }
     ]
    },
    {
     "title": "More info: TCP + IP pair + Port pair + Ground truth",
     "type": "table",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"window-multi-rf\" and (r._field == \"tcp_header_size\" or r._field == \"ground_truth\"))\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group(columns: [\"ip_src_port\", \"ip_dst_port\", \"ip_src_addr\", \"ip_dst_addr\", \"ground_truth\"])\r\n  |> mean(column: \"tcp_header_size\")\r\n  |> map(fn: (r) => ({ tcp_header_size: r.tcp_header_size, ip_port: r.ip_src_port + \" -> \" +  r.ip_dst_port, ip_pair: r.ip_src_addr + \" -> \" +  r.ip_dst_addr, ground__truth: r.ground_truth}))\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Number packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heatmap packets per IP pair",
     "type": "heatmap",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"window-multi-rf\" and r._field == \"window_pkt_count\")\r\n  |> group(columns: [\"_time\", \"ip_dst_addr\", \"ip_src_addr\"])\r\n  |> sum()\r\n  |> rename(columns: {\"ip_src_addr\": \"_src\", \"ip_dst_addr\": \"dst\"})\r\n  |> map(fn: (r) => ({ time: r._time, \"_src\": r._src, dst: r.dst, \"\": r._value}))"
      }
     ]
    },
    {
     "title": "IP pair (src -> dst)",
     "type": "barchart",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"window-multi-rf\" and r._field == \"window_pkt_count\")\r\n  |> group(columns: [\"ip_src_addr\", \"ip_dst_addr\"])\r\n  |> sum()\r\n  |> map(fn: (r) => ({ packets: r._value, _field: r.ip_src_addr + \" -> \" +  r.ip_dst_addr}))\r\n"
      }
     ]
    },
    {
     "title": "IP Source Address",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "from(bucket: \"default\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._measurement == \"window-multi-rf\" and r._field == \"window_pkt_count\")\r\n|> group(columns: [\"ip_src_addr\"])\r\n|> sum()\r\n|> map(fn: (r) => ({ packets: r._value, _field: r.ip_src_addr}))"
      }
     ]
    },
    {
     "title": "IP Destination Address",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "from(bucket: \"default\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._measurement == \"window-multi-rf\" and r._field == \"window_pkt_count\")\r\n|> group(columns: [\"ip_dst_addr\"])\r\n|> sum()\r\n|> map(fn: (r) => ({ packets: r._value, _field: r.ip_dst_addr }))"
      }
     ]
    },
    {
     "title": "Port pair (src -> dst)",
     "type": "barchart",
     "description": "Limit to ports with more than 30 packets",
     "gridPos": { "h": 19, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"window-multi-rf\" and r._field == \"window_pkt_count\")\r\n  |> group(columns: [\"ip_src_port\", \"ip_dst_port\"])\r\n  |> sum()\r\n  |> filter(fn: (r) => r._value > 30)\r\n  |> map(fn: (r) => ({ ip_data_size: r._value, ip_port: r.ip_src_port + \" -> \" +  r.ip_dst_port}))\r\n"
      }
     ]
    },
    {
     "title": "IP Source Port",
     "type": "barchart",
     "description": "Limit to ports with more than 30 packets",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "query": "from(bucket: \"default\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._measurement == \"window-multi-rf\" and r._field == \"window_pkt_count\")\r\n|> group(columns: [\"ip_src_port\"])\r\n|> sum()\r\n|> filter(fn: (r) => r._value > 30)\r\n|> map(fn: (r) => ({ packets: r._value, _field: r.ip_src_port }))"
      }
     ]
    },
    {
     "title": "IP Destination Port",
     "type": "barchart",
     "description": "Limit to ports with more than 30 packets",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "query": "from(bucket: \"default\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._measurement == \"window-multi-rf\" and r._field == \"window_pkt_count\")\r\n|> group(columns: [\"ip_dst_port\"])\r\n|> sum()\r\n|> filter(fn: (r) => r._value > 30)\r\n|> map(fn: (r) => ({ packets: r._value, _field: r.ip_dst_port }))"
      }
     ]
    },
    {
     "title": "Size of packets",
     "type": "piechart",
     "gridPos": { "h": 16, "w": 6, "x": 0, "y": 54 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"window-multi-rf\" and r._field == \"window_pkt_count\")\r\n  |> duplicate(column: \"_value\", as: \"value\")\r\n  |> keep(columns: [\"_value\", \"value\"])\r\n  |> group(columns: [\"value\"])\r\n  |> count()\r\n  |> rename(columns: {\"_value\": \"\"})\r\n\r\n"
      }
     ]
    },
    {
     "title": "More info: IP pair + Port pair + Ground truth",
     "type": "table",
     "gridPos": { "h": 16, "w": 18, "x": 6, "y": 54 },
     "targets": [
      {
       "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"window-multi-rf\" and (r._field == \"window_pkt_count\" or r._field == \"ground_truth\"))\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group(columns: [\"ip_src_port\", \"ip_dst_port\", \"ip_src_addr\", \"ip_dst_addr\", \"ground_truth\"])\r\n  |> sum(column:\"window_pkt_count\")\r\n  |> map(fn: (r) => ({ packets: r.window_pkt_count, ip_port: r.ip_src_port + \" -> \" +  r.ip_dst_port, ip_pair: r.ip_src_addr + \" -> \" +  r.ip_dst_addr, ground__truth: r.ground_truth}))\r\n\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Others",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Arrival avg - Packet size avg",
     "type": "xychart",
     "gridPos": { "h": 14, "w": 11, "x": 0, "y": 5 },
     "targets": [
      {
       "query": "from(bucket: \"default\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._measurement == \"window-multi-rf\")\r\n|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n|> map(fn: (r) => ({ time: r._time, \"window_avg_pkt_size\": r.window_avg_pkt_size, window_inter_arrival_avg: r.window_inter_arrival_avg, dst: r.ip_dst_addr, src: r.ip_src_addr}))\r\n\r\n"
      }
     ]
    }
   ]
  }
 ]
}