version: '3.7'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    restart: always
    network_mode: host
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_PORT:-2181}
      ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: confluentinc/cp-kafka:7.2.1
    restart: always
    network_mode: host
    hostname: ${BROKER_HOSTNAME:?hostname advertised by kafka}
    container_name: broker
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:${ZOOKEEPER_PORT:-2181}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: OUTSIDE:PLAINTEXT,INSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: OUTSIDE://${BROKER_HOSTNAME}:${OUTSIDE_BROKER_PORT},INSIDE://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: ${BROKER_HOSTNAME}
    env_file: .env
    command: "/etc/confluent/docker/run"
  packet-capture:
    image: kafka-pcap:latest
    network_mode: host
    hostname: kafka-pcap
    container_name: kafka-pcap
    environment:
      DESTINATION_PORT: ${OUTSIDE_BROKER_PORT}
      PCAP_MAX_PACKET_COUNT: ${MAX_PACKET_COUNT}
    volumes:
      - type: volume
        source: pcap-capture
        target: /pcap
volumes:
  pcap-capture:
    external: true
